export const GET_POSTS_START = 'GET_POSTS_START';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';
export const USER_ID_CHANGE = 'USER_ID_CHANGE';
export const CLICKED_POST_SAVE = 'CLICKED_POST_SAVE';
export const GET_COMMENTS_START = 'GET_COMMENTS_START';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
